
#ifndef __WORDLIST_H__
#define __WORDLIST_H__

// This file is autogenerated by running `ruby ./words/words.rb`

extern const unsigned char data[];
extern const unsigned short wordlen[3][16];
extern const unsigned int wordpos[3][16];

extern const unsigned char doubleAbsorbOffset[];
extern const unsigned char doubleAbsorbLen[3][16];
extern const unsigned short doubleAbsorbPos[3][16];

#define NUM_BANKS 3
#define NUM_WORDS 16

#endif
