
#ifndef __WORDLIST_H__
#define __WORDLIST_H__

// This file is autogenerated by running `ruby ./words/words.rb`

extern const unsigned char data[];
extern const unsigned short wordlen[2][16];
extern const unsigned int wordpos[2][16];

extern const unsigned char validOffset[];
extern const unsigned char validOffsetLen[2][16];
extern const unsigned short validOffsetPos[2][16];

#define NUM_BANKS 2
#define NUM_WORDS 16

#endif
