
#ifndef __WORDLIST_H__
#define __WORDLIST_H__

// This file is autogenerated by running `ruby ./words/words.rb`

extern const unsigned char data[];
extern const unsigned char wordlen[1][16];
extern const unsigned short wordpos[1][16];

#define NUM_BANKS 1
#define NUM_WORDS 16

#endif
